const hub = 'https://tabellone-produzione-liv-e313e.firebaseapp.com/';
const entries = [
  ['amz-freight', 'AMZ FREIGHT', 'https://freight.amazon.de/shipments/booked', 'freight'],
  ['shopify', 'shopify verdecobre', 'https://admin.shopify.com/store/63fbdc-fa', 'shopify'],
  ['amazon-seller', 'seller amazon', 'https://sellercentral.amazon.it/gp/homepage.html', 'amazon'],
  ['amazon-developer', 'developer console amazon', 'https://solutionproviderportal.amazon.com/sellingpartner/developerconsole', 'amazon'],
  ['facebook', 'centro inser fb', 'https://www.facebook.com/61587585715563/ad_center/?ref_source=www_profile_plus_left_nav_ad_center_button', 'facebook'],
  ['hub', 'hub centrale', hub, 'hub'],
  ['etichette', 'etichette amazon', hub + 'thermal_print_app_v2.html', 'hub'],
  ['ilovepaghe', 'ilovepaghe', 'https://www.ilovepaghe.com/', 'ilovepaghe'],
  ['capannone', 'capannone 3d', hub + 'capannone_3d.html', 'blank'],
  ['test-ios', 'test account ios', 'https://cedoly-test-221239281658.europe-west1.run.app/', 'test'],
  ['trading', 'LG Trading PAPER', 'https://united-axle-481817-q7.web.app/', 'trading'],
  ['trading-dev', 'LG Trading sviluppo', 'https://lg-trading-dev-2026.web.app/', 'trading'],
  ['lg-sito', 'LG Trading sito', 'https://www.lgtrading.it/', 'lg'],
  ['crm', 'Cedoly CRM', 'https://cedoly-crm-prod.web.app/', 'cedoly'],
  ['cedoly-gestore', 'Cedoly gestore', 'https://cedoly.it/admin', 'cedoly'],
  ['cedoly-dipendente', 'Cedoly dipendente', 'https://cedoly.it/dash-utente', 'cedoly'],
  ['cedoly-iscritti', 'Cedoly iscritti', 'https://cedoly.it/superadmin', 'cedoly'],
  ['cedoly-assistenza', 'Cedoly assistenza', 'https://cedoly.it/admin#/supporto-operatore', 'cedoly'],
  ['cedoly-sito', 'Cedoly sito', 'https://cedoly.it/', 'cedoly'],
  ['ilovepaghe-gestore', 'iLovePaghe gestore', 'https://www.ilovepaghe.com/dash-admin-split/dash-admin-dashboard', 'ilovepaghe'],
  ['bionee', 'Bionee', 'https://bionee.it/', 'bionee'],
  ['motorclub', 'LG Motorclub', 'https://lg-motorclub-prod.web.app/', 'motorclub'],
  ['motorclub-gestione', 'Motorclub gestione', 'https://lg-motorclub-prod.web.app/admin', 'motorclub'],
  ['picking', 'Picking', hub + 'picking.html', 'hub'],
  ['ubicazioni', 'Ubicazioni', hub + 'ubicazione.html', 'hub'],
  ['gestionale', 'Gestionale inventario', hub + 'hub_inventario.html', 'hub'],
  ['inventario-amazon', 'Inventario Amazon', hub + 'hub_inventario_amazon.html', 'hub'],
  ['inventario-conca', 'Inventario Concamarise', hub + 'INVENTARIO_CONCAMARISE.html', 'hub'],
  ['inventario-prisma', 'Inventario Prisma', hub + 'INVENTARIO_PRISMA.html', 'hub'],
  ['polveri', 'Linea polveri', hub + 'hub_linea_polveri.html', 'hub'],
  ['liquidi-auto', 'Liquidi automatica', hub + 'tabellone_write.html', 'hub'],
  ['liquidi-manuale', 'Liquidi manuale', hub + 'hub_linea_liquidi.html', 'hub'],
  ['estrusore', 'Estrusore flaconi', hub + 'ESTRUSORE_FLACONI_1LT.html', 'hub'],
  ['bulk', 'Bulk 1000 L', hub + 'bulk_produzioni_write.html', 'hub'],
  ['granulari', 'Granulari', hub + 'hub_granulari.html', 'hub'],
  ['agenti', 'Ordini agenti', hub + 'hub_ordini_agenti.html', 'hub'],
  ['ordini-amazon', 'Ordini Amazon', hub + 'amazon-ordini.html', 'hub'],
  ['amazon-monitor', 'Amazon Live Monitor', hub + 'amz-monitor.html', 'hub'],
  ['capannone-controller', 'Controller capannone', hub + 'controller_capannone_3d.html', 'hub'],
  ['pdf', 'Editor PDF', hub + 'LETTOREPDF.html', 'hub'],
  ['buste-paga', 'Hub buste paga', hub + 'hub_buste_paga_admin.html', 'hub']
];
export const defaults = entries.map(([id, name, url, icon]) => ({ id, name, url, icon }));
